"""initial_migration

Revision ID: 079a8d2b0d86
Revises: 
Create Date: 2025-01-31 06:23:46.284599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '079a8d2b0d86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_used_tokens_id', table_name='used_tokens')
    op.drop_index('ix_used_tokens_token', table_name='used_tokens')
    op.drop_table('used_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='used_tokens_pkey')
    )
    op.create_index('ix_used_tokens_token', 'used_tokens', ['token'], unique=False)
    op.create_index('ix_used_tokens_id', 'used_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
